routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::view('/', 'welcome');

Auth::routes();

Route::resource('categories.products', 'ProductController');

Route::resources([
    'categories' => 'CategoryController',
    'products' => 'ProductController',
]);

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Kalnoy\Nestedset\NodeTrait;

class Category extends Model
{
    use NodeTrait;
    
    protected $fillable = ['name', 'alias', 'parent_id', '_lft', '_rgt'];
    
    public function products()
    {
        return $this->hasMany(Product::class, 'category_id');
    }
    
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Http\Request;
use App\Taverse;

class CategoryController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Taverse $traverse) {

//        debug_print_backtrace(2);
//        $node = Category::create([
//                    'name' => 'Women',
//                    'alias' => 'women',
//                    'children' => [
//                        [
//                            'name' => 'Dresses',
//                            'alias' => 'dresses',
//                            'children' => [
//                                ['name' => 'Cocktails','alias' => 'cocktails',],
//                            ],
//                        ],
//                    ],
//        ]);
        //include(app_path() . '\Functions\functions.php');

        $categories = Category::withDepth()->where('parent_id', '=', null)->get();

        return view('categories.index', [
            'categories' => $categories,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request) {

        $parentCategoryId = $request->input('clickedCategory');
        $parentCategory = Category::find($parentCategoryId);

        return view('categories.create', [
            'parentCategory' => $parentCategory,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {

        Category::create($request->all());

        return redirect()->action('CategoryController@index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category) {

        $categories = Category::withDepth()->where('parent_id', '=', null)->get();
        $requestedCategory = Category::withDepth()->find($category->id);
        $ancestorsIds = $category->ancestors()->pluck('id');

        if (count($ancestorsIds) > 0) {
            $parentOfRequestedCategoryCollection = Category::withDepth()->descendantsAndSelf($ancestorsIds[0])->toTree();
        } else {
            $parentOfRequestedCategoryCollection = Category::withDepth()->descendantsAndSelf($category->id)->toTree();
        }
        
        $parentOfRequestedCategory = $parentOfRequestedCategoryCollection[0];


        return view('categories.show', [
            'categories' => $categories,
            'parentOfRequestedCategory' => $parentOfRequestedCategory,
            'requestedCategory' => $requestedCategory,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category) {
        
        return view('categories.edit', [
            'category' => $category,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category) {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category) {
        $category->delete();
        return redirect()->back();
    }

}

resources/views/categories/corecursive.blade.php
<option value="{{ $category->id }}">
@for ($i = 0; $i < $category->depth; $i++)
    -
@endfor
{{$category->name}}
@if (count($category->children )> 0)
       
            @each('categories.corecursive', $category->children, 'category')
       
@endif
</option>

resources/views/categories/create.blade.php
@extends('layouts.app')

@section('content')

<!-- Bootstrap Boilerplate... -->
<div class="panel-body">
    <!-- Display Validation Errors -->
    @include('common.errors')
    <!-- New Subject Form -->
    <form action="{{ url('categories') }}" method="POST" class="form-horizontal">
        {{ csrf_field() }}
        <div class="form-group">
            <label for="category-name" class="col-sm-3 control-label">
                category
            </label>
            <div class="col-sm-6">
                <input type="text" name="name" id="category-name" class="form-control">
            </div>
            <label for="category-alias" class="col-sm-3 control-label">
                alias
            </label>
            <div class="col-sm-6">
                <input type="text" name="alias" id="category-alias" class="form-control">
            </div>
            @if (request("clickedCategory"))
            <label for="category-parent" class="col-sm-3 control-label">
                selected 
            </label>
            <div class="col-sm-6">            
                <input id="category-parent" class="form-control" disabled="" value="{{$parentCategory->name}}">
                <input hidden="" name="parent_id" value="{{$parentCategory->id}}">  
            </div>            
            @endif
        </div>

        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-6">
                <button type="submit" class="btn btn-default">
                    <i class="fa fa-plus">Add category</i>
                </button>
            </div>
        </div>
    </form>
</div>
@endsection

resources/views/categories/edit.blade.php
@extends('layouts.app')
@section('content')

<div class="panel-body">

    <form action="{{ route('categories.update', [$category]) }}" method="POST" class="form-horizontal">
        {{ csrf_field() }}
        @method('PUT')
        <div class="form-group">
            <label for="category-name" class="col-sm-3 control-label">
                category
            </label>
            <div class="col-sm-6">
                <input type="text" name="name" value="{{ $category->name }}" id="category-name" class="form-control">
            </div>
            <label for="category-alias" class="col-sm-3 control-label">
                alias
            </label>
            <div class="col-sm-6">
                <input type="text" name="alias" value="{{ $category->alias }}" id="category-alias" class="form-control">
            </div>
            <label for="category-parent" class="col-sm-3 control-label">
                parent 
            </label>
                     
        </div>

        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-6">
                <button type="submit" class="btn btn-default">
                    <i class="fa fa-plus">Add category</i>
                </button>
            </div>
        </div>
    </form>
</div>
@endsection

resources/views/categories/index.blade.php
@extends('layouts.app')

@section('content')

@if(count($categories) > 0)
<!-- Current categories -->
<div class="panel panel-default">  
    <ul>
        @foreach($categories as $category)  
        <li  style="margin-bottom: 20px;">      
            <a  href="{{ route('categories.show', [$category]) }}">{{$category->name}}</a>            
            <form style="display: inline;" action="{{ url('categories/create') }}" method="GET" class="form-horizontal">
                {{ csrf_field() }}
                <input hidden="" name="clickedCategory" value="{{$category->id}}">
                <button  type="submit" class="btn btn-default">
                    <i class="fa fa-plus">+</i>
                </button>
            </form>
            <form style="display: inline;" action="{{ route('categories.destroy', [$category]) }}" method="POST" class="form-horizontal">
                @method('DELETE')
                {{ csrf_field() }}
                <button  type="submit" class="btn btn-default">
                    <i class="fa fa-plus">delete</i>
                </button>
            </form>
            <form style="display: inline;" action="{{ route('categories.edit', [$category]) }}" method="GET" class="form-horizontal">              
                <button  type="submit" class="btn btn-default">
                    <i class="fa fa-plus">edit</i>
                </button>
            </form>
            <form style="display: inline;" action="{{url('categories/'. $category->id. '/products') }}"  method="GET" class="form-horizontal">              
                <button  type="submit" class="btn btn-default">
                    <i class="fa fa-plus">see products</i>
                </button>
            </form>
        </li>     
        @endforeach
    </ul>
</div>
@endif

<div class="panel-body"> 
    <!-- To New Category Form -->
    <form action="{{ url('categories/create') }}" method="GET" class="form-horizontal">
        {{ csrf_field() }}

        <!-- Go To create Button -->
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-6">
                <button type="submit" class="btn btn-default">
                    <i class="fa fa-plus"></i> New category
                </button>
            </div>
        </div>
    </form>
</div>

@endsection

resources/views/categories/indexOld.blade.php
@extends('layouts.app')

@section('content')

<!-- Current categories -->
<div class="panel panel-default">

    @if($categories)
    <ul>
        @each('categories.recursive', $categories, 'category')
    </ul>
    @endif

</div>

<div class="panel-body"> 
    <!-- To New Category Form -->
    <form action="{{ url('categories/create') }}" method="GET" class="form-horizontal">
        {{ csrf_field() }}

        <!-- Go To create Button -->
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-6">
                <button type="submit" class="btn btn-default">
                    <i class="fa fa-plus"></i> New category
                </button>
            </div>
        </div>
    </form>
</div>

@endsection

resources/views/categories/recursive.blade.php
<li style="margin-bottom: 20px;">    
    <a  href="{{ route('categories.show', [$category]) }}">{{$category->name}}</a>
    <form style="display: inline;" action="{{ url('categories/create') }}" method="GET" class="form-horizontal">
        {{ csrf_field() }}
        <input hidden="" name="clickedCategory" value="{{$category->id}}">
        <button  type="submit" class="btn btn-default">
            <i class="fa fa-plus">+</i>
        </button>
    </form>
    <form style="display: inline;" action="{{ route('categories.destroy', [$category]) }}" method="POST" class="form-horizontal">
        @method('DELETE')
        {{ csrf_field() }}
        <button  type="submit" class="btn btn-default">
            <i class="fa fa-plus">delete</i>
        </button>
    </form>
    <form style="display: inline;" action="{{ route('categories.edit', [$category]) }}" method="GET" class="form-horizontal">              
        <button  type="submit" class="btn btn-default">
            <i class="fa fa-plus">edit</i>
        </button>
    </form>
    <form style="display: inline;" action="{{url('categories/'. $category->id. '/products') }}"  method="GET" class="form-horizontal">              
        <button  type="submit" class="btn btn-default">
            <i class="fa fa-plus">see products</i>
        </button>
    </form>
    @if (count($category->children)>0)
    @foreach ($category->children as $category)
    <ul style="margin-bottom: 20px; margin-top: 20px;">     
        @if($category->depth <= $requestedCategory->depth+1)
            @include('categories.recursive', ['category' => $category,'requestedCategory' => $requestedCategory])
        @endif 
    </ul>   
    @endforeach
    @endif 
</li>

resources/views/categories/show.blade.php
@extends('layouts.app')

@section('content')

@if(count($categories) > 0)
<!-- Current categories -->
<div class="panel panel-default">  
    <ul>
        @foreach($categories as $category)
        @if($category->id == $parentOfRequestedCategory->id)  
            @include('categories.recursive', ['category' => $parentOfRequestedCategory,'requestedCategory' => $requestedCategory])
        @else
        <li style="margin-bottom: 20px;">                  
            <a  href="{{ route('categories.show', [$category]) }}">{{$category->name}}</a>     
            <form style="display: inline;" action="{{ url('categories/create') }}" method="GET" class="form-horizontal">
                {{ csrf_field() }}
                <input hidden="" name="clickedCategory" value="{{$category->id}}">
                <button  type="submit" class="btn btn-default">
                    <i class="fa fa-plus">+</i>
                </button>
            </form>
            <form style="display: inline;" action="{{ route('categories.destroy', [$category]) }}" method="POST" class="form-horizontal">
                @method('DELETE')
                {{ csrf_field() }}
                <button  type="submit" class="btn btn-default">
                    <i class="fa fa-plus">delete</i>
                </button>
            </form>
            <form style="display: inline;" action="{{ route('categories.edit', [$category]) }}" method="GET" class="form-horizontal">              
                <button  type="submit" class="btn btn-default">
                    <i class="fa fa-plus">edit</i>
                </button>
            </form>
             <form style="display: inline;" action="{{url('categories/'. $category->id. '/products') }}"  method="GET" class="form-horizontal">              
                <button  type="submit" class="btn btn-default">
                    <i class="fa fa-plus">see products</i>
                </button>
            </form>
        </li>
        @endif
        @endforeach
    </ul>
</div>
@endif

<div class="panel-body"> 
    <!-- To New Category Form -->
    <form action="{{ url('categories/create') }}" method="GET" class="form-horizontal">
        {{ csrf_field() }}

        <!-- Go To create Button -->
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-6">
                <button type="submit" class="btn btn-default">
                    <i class="fa fa-plus"></i> New category
                </button>
            </div>
        </div>
    </form>
</div>

@endsection