routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::view('/', 'welcome');

Auth::routes();

Route::resource('categories.products', 'ProductController');

Route::resources([
    'categories' => 'CategoryController',
    'products' => 'ProductController',
]);

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = ['name', 'alias', 'image', 'description', 'price', 'category_id'];
    
    public function category() {
        return $this->belongsTo(Category::class, 'category_id');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Models\Category;
use Illuminate\Http\Request;

class ProductController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Category $category) {

        $categories = $category->descendants()->pluck('id');
        $categories[] = $category->getKey();
        $products = Product::with('category')->whereIn('category_id', $categories)->get();

        return view('products.index', [
            'products' => $products,
            'category' => $category,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Category $category) {

        return view('products.create', [
            'category' => $category,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Category $category) {

        Product::create($request->all());
        return redirect()->route('categories.products.index', [$category]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product) {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product) {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product) {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product) {
        //
    }

}

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')

<div class="panel-body">

    <form action="{{route('categories.products.store', [$category])}}" method="POST" class="form-horizontal">
        {{ csrf_field() }}
        <div class="form-group">
            <label for="product-name" class="col-sm-3 control-label">
                product
            </label>
            <div class="col-sm-6">
                <input type="text" name="name" id="product-name" class="form-control">
            </div>
            <label for="product-alias" class="col-sm-3 control-label">
                alias
            </label>
            <div class="col-sm-6">
                <input type="text" name="alias" id="product-alias" class="form-control">
            </div> 
            <label for="product-price" class="col-sm-3 control-label">
                price
            </label>
            <div class="col-sm-6">
                <input type="text" name="price" id="product-price" class="form-control">
            </div> 
            <label for="product-description" class="col-sm-3 control-label">
                description
            </label>
            <div class="col-sm-6">
                <textarea name="description" id="product-alias" class="form-control"></textarea>
            </div>    
            <label for="product-parent" class="col-sm-3 control-label">
                category 
            </label>
            <div class="col-sm-6">            
                <input id="product-parent" class="form-control" disabled="" value="{{$category->name}}">
                <input hidden="" name="category_id" value="{{$category->id}}">  
            </div>            
        </div>

        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-6">
                <button type="submit" class="btn btn-default">
                    <i class="fa fa-plus">Add product</i>
                </button>
            </div>
        </div>
    </form>
</div>
@endsection

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')

<!-- Current categories -->
<div class="panel panel-default">

    @if(count($products) > 0)
    <div class="productsContainer">
    @foreach($products as $iterator=> $product)

    @if( 0 == $iterator % 5 ) 
    </div>
    <div class="productsContainer">
        <div class="productsItem">
            <div>{{$product->image}}</div> 
            <div>{{$product->name}}</div> 
            <div>{{$product->description}}</div>
            <div>{{$product->price}}</div>
            <div>{{$product->category->name}}</div>
        </div>    
    @else
        <div class="productsItem">
            <div>{{$product->image}}</div> 
            <div>{{$product->name}}</div> 
            <div>{{$product->description}}</div>
            <div>{{$product->price}}</div>
            <div>{{$product->category->name}}</div>
        </div>
    @endif        
    @endforeach
    </div>
    @endif

    </div>

    <div clas    s="panel-body"> 
        <!-- To New Category Form -->
        <form action="{{ route('categories.products.create', [$category]) }}" 
              method="GET" class="form-horizontal">
            <div class="form-group">
                <div class="col-sm-offset-3 col-sm-6">
                    <button type="submit" class="btn btn-default">
                        <i class="fa fa-plus">New Product</i>
                    </button>
                </div>
            </div>
        </form>
    </div>

    @endsection